# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: snagsby
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/roverdotcom/snagsby/pkg.Version={{.Version}}
    binary: snagsby

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}.
      {{- .Os }}-
      {{- .Arch }}
    files:
      # Include only the binary, no extra files
      - none*

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

# Disable source archives as they weren't part of the original build
source:
  enabled: false
