steps:
  - command: 'make docker-test'
    label: ':docker: Test'

  - command: python .buildkite/pipeline.py | buildkite-agent pipeline upload
    label: ':docker: Load e2e steps'

  - wait

  - command: 'make clean && make docker-dist && make fpm'
    label: ':docker: BUILD'
    artifact_paths:
      - 'dist/*'
